package com.example.fceytentusmanos.Carreras;

public class Obj_Carreras {

    private String nombreCarrera, Departamento, Duracion, telefono, direccion, website, perfilProfesional;

    public String getNombreCarrera() {
        return nombreCarrera;
    }

    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }

    public String getDepartamento() {
        return Departamento;
    }

    public void setDepartamento(String departamento) {
        Departamento = departamento;
    }

    public String getDuracion() {
        return Duracion;
    }

    public void setDuracion(String duracion) {
        Duracion = duracion;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getPerfilProfesional() {
        return perfilProfesional;
    }

    public void setPerfilProfesional(String perfilProfesional) {
        this.perfilProfesional = perfilProfesional;
    }



    public Obj_Carreras(String nombreCarrera, String departamento, String duracion, String telefono, String direccion, String website, String perfilProfesional) {
        this.nombreCarrera = nombreCarrera;
        Departamento = departamento;
        Duracion = duracion;
        this.telefono = telefono;
        this.direccion = direccion;
        this.website = website;
        this.perfilProfesional = perfilProfesional;
    }

    public Obj_Carreras[] cargarArregloCarreras() {
        Obj_Carreras[] ArregloCarreras = new Obj_Carreras[]{
                //Ingenierias
                new Obj_Carreras("Ingenieria Civil", "Dpto. de Estructura y Construcciones", "5 años", " 385 450 9560   Int 1921", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-civil", "El Ingeniero Civil es un profesional idóneo, comprometido con la realización y evolución de sí mismo y con el medio inmediato donde actúa, como así, con el grupo nacional al que pertenece el Estado que jurídicamente regula y ordena su comportamiento. Es preciso que esté dispuesto a constituirse en un generador dinámico y dinamizante en su contorno existencial y que en este caso particular se entronca con las necesidades de la región. El Ingeniero Civil debe tener capacidad para estudiar, proyectar, construir, mantener y dirigir todo tipo de estructuras, emprendimientos hidráulicos, hídricos y sistemas hidráulicos, sanitarios y de riego, de aprovechamiento energético, obras de caminos y ferrocarriles."),
                new Obj_Carreras("Ingenieria Electromecanica", "Dpto. de Mecanica", "5 años", " 385 450 9560   Int 1901", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-electromecanica", "El Ingeniero Electromecánico en consonancia con sus conocimientos, capacidades y habilidades adquiridas está en condiciones de:\nAcometer con capacidad teórica y actitud innovadora los problemas técnicos y los cambios tecnológicos de su área de alcance.\nReconocer las tecnologías vigentes, seleccionar, manejar, crear y desarrollar nuevas tecnologías.\nDistinguir los niveles de jerarquía de un sistema electromecánico general e integrarlo a sistemas de diversos grados de complejidad, analizando y evaluando con métodos propios de la ingeniería.\nUsar las técnicas y herramientas informáticas.\nInterpretar variables económicas y sus efectos en la producción, la empresa y la sociedad.\nAfrontar la actualización permanente requerida por su especialidad.\nExpresar una actitud ética en su trabajo y demás actividades sociales.\nExpresar una actitud de compromiso con valores como la preservación del medio ambiente y la economía de recursos."),
                new Obj_Carreras("Ingenieria Electronica", "Dpto. de Electronica", "5 años", " 385 450 9560   Int 1910", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-electronica", "El Ingeniero Electrónico es un profesional idóneo, comprometido con la realización y evolución de sí mismo y con el medio donde actúa, constituyéndose en un sujeto dinámico y dinamizante. Tiene dominio sobre los principios de las ciencias exactas para ser usados en distintas áreas de aplicación de la electrónica tales como: control, automatización, electrónica industrial, instrumentación e informática aplicada.\nAdquiere nociones básicas sobre, gestión, formulación y evaluación de proyectos, y sobre administración de recursos humanos. Puede demostrar su creatividad aplicando el saber adquirido a la resolución de problemas concretos como a la generación de nuevas tecnologías. Posee conocimientos complementarios que le permiten abordar con propiedad, desde una perspectiva humanista, las complejas relaciones legales, económicas y financieras que impone el  mundo moderno."),
                new Obj_Carreras("Ingenieria Electrica", "Dpto. de Electricidad", "5 años", " 385 450 9560   Int 1836", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-electrica", "El Ingeniero Eléctrico es un profesional idóneo, capacitado en las ciencias básicas, en las tecnologías eléctricas y su aplicación al campo de la generación, transporte, distribución, despacho y utilización de la energía eléctrica. Posee nociones básicas sobre gestión, administración de recursos humanos y formulación y evaluación de proyectos. Es creativo, aplica el saber adquirido en la resolución de problemas concretos, como así también en la generación de nuevas tecnologías. Aborda con propiedad y desde una perspectiva humanista, las complejas relaciones legales y económicas que impone el mundo moderno. Manifiesta una actitud ética y de compromiso en su trabajo, con valores como la preservación del medio ambiente y la economía de recursos."),
                new Obj_Carreras("Ingenieria en Agrimensura", "Dpto. de Agrimensura", "5 años", " 385 450 9560 Int 1832", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-en-agrimensura", "Responder a los requerimientos del medio desde el punto de vista del asesoramiento, planificación, dirección y ejecución de trabajos de la especialidad, desarrollar tareas de investigación relacionadas con su profesión y docencia relativa al Agrimensor, en sus diversos niveles.\nResponder en las distintas áreas que componen este definido campo del saber que es la Agrimensura y que está integrado fundamentalmente por: el área Geo-Foto-Topo-Cartográfica, el área Geomorfológica y el área Económica, Jurídica y Social. Estas áreas adecuadamente complementadas posibilitan los dos objetivos fundamentales de la Agrimensura: el Conocimiento y Representación Cartológica de la Superficie Terrestre y el Ordenamiento Territorial, a través de la determinación de la aplicación material de los límites territoriales.\nIntegrar equipos interdisciplinarios a nivel de proyectos, de planificaciones y ejecuciones de tipo profesional.\n"),
                new Obj_Carreras("Ingenieria Hidraulica", "Dpto. de Recursos Hidricos", "5 años", " 385 450 9560   Int 1908", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-hidraulica", "El Ingeniero Hidráulico es un profesional de la Ingeniería que está capacitado para realizar tareas relacionadas con la especialidad, bien sean estas específicas de la hidráulica o afines a ella, y tareas de apoyo tales como:\nEspecíficas: Estudios, Proyectos, Dirección, Construcción, Explotación y Mantenimiento de: Obras de Riego, Drenaje, Desagües Urbanos y Rurales; Captación, Tratamiento y Distribución de Aguas para todo tipo de Consumos; Estructuras Hidráulicas, Azudes, Presas, Embalses; Obras Fluviales, Corrección de Torrentes; Estudios de Crecidas.\nAfines: Trabajos Topográficos; Geotécnia; Aspectos Legales, Económicos y Financieros; Evaluación de Impacto Ambiental; Pericias. Por otra parte su formación básica le permitirá abordar actividades de Investigación y Desarrollo, ya sea a través de proyectos de carácter científico, o de desarrollo tecnológico en la disciplina Hidráulica.\n"),
                new Obj_Carreras("Ingenieria Industrial", "Dpto. de Estructura y Construcciones", "5 años", " 385 450 9560", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-industrial", "La carrera de Ingeniería Industrial procura formar profesionales capaces de desempeñarse en funciones de gestión organizativa, de desarrollo y operativa en entornos productivos, teniendo presente los contextos local, regional, nacional y mundial, incorporando creatividad e innovación al elaborar soluciones y haciéndolo con sentido ético y humanístico para preservar el patrimonio ambiental y cultural.\nSus egresados están capacitados para implementar, evaluar, organizar y conducir sistemas productivos y áreas operativas, aplicando diversas técnicas, recursos humanos, materiales, equipos, máquinas e instalaciones, con el objeto de ordenar económica y productivamente empresas de bienes y servicios, cuyo objetivo es satisfacer necesidades de la sociedad. Los mismos se espera que estén capacitados para vincular los sectores productivos, económicos, administrativos y del mercado, comunicarse adecuadamente con economistas, ingenieros especialistas y administradores de empresas (entre otros profesionales) y también puedan conducir requerimientos de reingeniería."),
                new Obj_Carreras("Ingenieria Vial", "Dpto. de Obras Viales", "5 años", " 385 450 9560   Int 1921", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=ingenieria-vial", "El Ingeniero Vial es un profesional de la ingeniería que está capacitado para el estudio, proyecto, dirección, construcción y gerenciamiento de obras viales urbanas y rurales, obras de arte, puentes, pistas de aeropuertos y trabajos topográficos relacionados con las tareas antes expuestas. También se encarga de proyectos de evaluación de estado y rehabilitación de las vías de comunicación. Realiza  experiencias de laboratorio para la investigación de suelos y diversos materiales usados en la ejecución de obras viales. \nAtiende asuntos de ingeniería legal, economía y finanzas, relacionadas con la explotación de la vía de comunicación."),
                //Licenciaturas
                new Obj_Carreras("","","","","","",""),
                new Obj_Carreras("Licenciatura en hidrologia subterranea", "Dpto. de Recursos Hidricos", "4 años", " 385 450 9560   Int 1908", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=licenciatura-en-hidrologia-subterranea", "El Licenciado en Hidrología Subterránea, es un profesional idóneo, comprometido con la realidad actual y futura, su evolución como tal y su relación con el medio inmediato donde actúa y al grupo nacional que pertenece, ajustando su desempeño a lo dispuesto por el Estado que jurídicamente regula y ordena su comportamiento.\nEl Egresado posee un conocimiento integral y coherente en hidrología de las aguas subterráneas para una adecuada fundamentación teórica de su quehacer profesional específico.\nTambién tiene una apropiada preparación y capacidad para conocer y evaluar los recurso hídricos subterráneos disponibles, comprender su aptitud y principios de explotación racional y preservación.\nEs portador de una sólida formación en metodología de la investigación en áreas de su especialidad, para alcanzar e interpretar su campo de aplicación y formar grupos interdisciplinarios."),
                new Obj_Carreras("Licenciatura en sistemas de informacion", "Dpto. de Informatica", "5 años", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=licenciatura-en-sistemas-de-informacion", "El Licenciado en Sistemas de Información es un profesional que posee:\nLos conocimientos básicos (lógico-matemáticos y computacionales) para una adecuada fundamentación teórica de su quehacer profesional específico.\nProfundos conocimientos, entre otros, sobre Teoría de Sistemas, Teoría de la Información y de la Comunicación, que le permiten fundamentar el diseño y aplicación de Sistemas de Información y Modelos.  \nUna sólida formación en metodología de investigación científica y sobre técnicas y procedimientos que le permiten indagar en el área de los Sistemas de Información y analizar e interpretar su campo de aplicación.\n"),
                new Obj_Carreras("Licenciatura en matematicas", "Dpto. de Matematica", "4 años", " 385 450 9560   Int 1921", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=lic-en-matematica", "El Licenciado en Matemática es un profesional que:\nPosee sólidos conocimientos teóricos y prácticos sobre la Ciencia Matemática y las disciplinas que componen su  campo del saber.\nEstá preparado para establecer relaciones con otros campos disciplinares con los que se vincula la Matemática.\nEstá en condiciones de efectuar interacciones con otras ciencias, desde la perspectiva de su formación para resolver problemas interdisciplinarios que demanden su intervención.\nDesarrolla conocimientos mediante su participación en la realización de estudios y en Proyectos de investigación aplicando el método científico\nAplica y recrea conocimientos para resolver problemas teórico - prácticos en los que se requiera la metodología de la ciencia Matemática.\nContribuye a la transmisión del conocimiento en la Universidad y en el nivel terciario no universitario.\n"),
                new Obj_Carreras("Licenciatura en matematicas (ciclo de complementacion)", "Dpto. de Matematica", "2 años y medio", " 385 450 9560   Int 1844", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=lic-en-matematica-cc", "El Licenciado en Matemática es un graduado que en el ejercicio de su profesión deberá realizar actividades en las que el manejo de herramientas de tipo teórico y formal constituirá su principal característica.\nDeberá ser capaz de:\nAbordar su campo de trabajo con la objetividad y el rigor propios de la ciencia que profesa.\nRealizar estudios de tipo teórico y poseer una forma de pensar que le permita la resolución de problemas mediante la manipulación de conceptos y entes formales.\nAdaptarse a los cambios científicos y tecnológicos que rápidamente se producen.\nIntegrar equipos interdisciplinarios y relacionar los temas propios de la matemática con otras disciplinas científicas.\nContribuir a la formación científica y humana de los estudiantes, por medio del ejercicio de la docencia.\n"),
                //Profesorados
                new Obj_Carreras("","","","","","",""),
                new Obj_Carreras("Profesorado de matematica", "Dpto. de Matematica", "4 años", " 385 450 9560   Int 1844", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=profesorado-en-matematica", "El Profesor en Matemática es un profesional que:\nPosee sólidos conocimientos teóricos y prácticos sobre la Ciencia Matemática y las disciplinas que componen su  campo del saber.\nEstá preparado para establecer relaciones con otros campos con los que se vincula la Matemática.\nEfectúa interacciones con otras ciencias, desde la perspectiva de su formación para resolver problemas interdisciplinarios que demanden su intervención.\nDesarrolla conocimientos mediante su participación en la realización de estudios y en proyectos de investigación aplicando el método científico.\nAplica y recrea conocimientos para resolver problemas teórico - prácticos en los que se requiera la metodología de la ciencia Matemática.\nContribuye a la transmisión del conocimiento mediante el ejercicio de la docencia en la Universidad en carrera de igual denominación o menor nivel (pregrado), en el nivel Terciario No universitario, en el tercer ciclo de la EGB y en el Nivel Polimodal."),
                new Obj_Carreras("Profesorado de Informatica", "Dpto. de Informatica", "4 años", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=profesorado-en-informatica", "El Profesor en Informática posee:\nSólidos conocimientos sobre, conducción, gestión, organización, desarrollo y evaluación del proceso de enseñanza - aprendizaje.\nCapacidad para analizar, desarrollar y aplicar sistemas relacionados con las Tecnologías Informáticas en el área educativa.\nConocimientos específicos sobre problemáticas psico-social del educando y sobre teorías del aprendizaje aplicadas al ámbito de la enseñanza de la Informática.\nCapacidad para seleccionar y aplicar un modelo curricular.\nSólidos conocimientos en el manejo y enseñanza de programas utilitarios.\nLos conocimientos básicos (lógico - matemáticos y computacionales) para una adecuada fundamentación teórica de su quehacer como profesional docente de la disciplina Informática.\nSólidos conocimientos sobre las teorías que sustentan a la Informática.\nProfundos conocimientos sobre teorías y técnicas de la programación.\nLa formación teórico - práctica necesaria para analizar y evaluar sistemas de información.\nHabilidad para seleccionar y aplicar los recursos informáticos al proceso de enseñanza - aprendizaje."),
                new Obj_Carreras("Profesorado de Fisica", "Dpto. de Fisica", "4 años", " 385 450 9560   Int 1835", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=profesorado-en-fisica", "El Profesor en Física es un profesional formado para:\nEnseñar Física en los niveles de educación secundaria y superior en contextos diversos.\nPlanificar, supervisar y evaluar procesos de enseñanza y aprendizaje en el área de la Física para los niveles de educación secundario y superior en contextos diversos.\nAsesorar en lo referente a las metodologías y a los procesos de la enseñanza de la Física. d) Diseñar, dirigir, integrar y evaluar diseños curriculares y proyectos de investigación e innovación educativas, relacionados con la Física.\nDiseñar, producir y evaluar materiales destinados a la enseñanza de Física.\nElaborar e implementar acciones destinadas al logro de la alfabetización científica en el campo de la Física.\nPlanificar, conducir, supervisar y evaluar proyectos, programas, cursos, talleres y otras actividades de capacitación, actualización y perfeccionamiento, orientadas a la formación docente continua en Física.\nDirigir, gestionar y supervisar laboratorios destinados a la enseñanza de la Física.\nDiseñar, implementar y evaluar proyectos pedagógicos, curriculares institucionales y de gestión educativa, vinculados con la enseñanza de la Física.\n"),
                //Carreras post-grado
                new Obj_Carreras("","","","","","",""),
                new Obj_Carreras("Especializacion en enseñanza en ciencias exactas", "Dpto. de Educación y Formación Complementaria", "14 meses", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=especializacion-en-ensenanza-en-ciencias-exactas", "Cuenta con sólidos conocimientos epistemológicos y didácticos en las Ciencias Exactas.\nSe encuentra capacitado para diseñar, implementar y evaluar proyectos de investigación en Enseñanza en Ciencias Exactas y tambien para proponer acciones, actividades y proyectos de mejoramiento de la calidad educativa de la Institución a la cual pertenece.\n"),
                new Obj_Carreras("Especializacion en enseñanza en tecnologias", "Dpto. de Educación y Formación Complementaria", "14 meses", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=especializacion-en-ensenanza-en-tecnologias", "Cuenta con sólidos conocimientos epistemológicos y didácticos en Tecnologías.\nSe encuentra capacitado para diseñar, implementar y evaluar proyectos de investigación en Enseñanza en Tecnologías también para proponer acciones, actividades y proyectos de mejoramiento de la calidad educativa de la Institución a la cual pertenece.\n"),
                new Obj_Carreras("Especialización en Hidráulica de Ríos", "Dpto. de Educación y Formación Complementaria", "500 horas", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=especializacion-en-hidraulica-de-rios", "El Especialista en Hidráulica de Ríos será un profesional postgraduado con sólidos conocimientos sobre el comportamiento de los sistemas fluviales, con capacidad para analizar los fenómenos hidráulicos y fluvio-morfológicos que ocurren en las zonas de influencia de ríos, tanto en su condición natural como alterada por la actividad humana. El mismo será capaz de aplicar distintas herramientas de simulación y modelación matemática y física a la solución de diversos problemas fluviales, de modo de obtener elementos cuantitativos que ayuden a la toma de decisiones para la optimización de proyectos de ingeniería en el ambiente fluvial. El especialista tendrá el nivel de conocimientos esencial para poder diseñar, conducir e implementar el desarrollo de innovaciones tecnológicas en el campo de la ingeniería de ríos."),
                new Obj_Carreras("Especialización en Higiene y Seguridad en el Trabajo", "Dpto. de Educación y Formación Complementaria", "544 horas", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=especializacion-en-higiene-y-seguridad-en-el-trabajo", "El Especialista en Higiene y Seguridad en el Trabajo será un profesional postgraduado, capaz de aplicar distintas herramientas legales, normativas y procedimentales , técnicas para el análisis e investigación de las situaciones laborales y el posterior diseño de soluciones de los diversos problemas que se presentan considerando para ello, además, el cuidado del ambiente laboral y la prevención de riesgos , a los fines de corregir las deficiencias de seguridad e higiene detectadas en los distintos lugares de trabajo. El Especialista podrá utilizar metodologías específicas para determinar y definir las necesidades de un medio ambiente en el trabajo, por medio de instrumentos y diagnósticos adecuados.\nEl Especialista en Higiene y Seguridad en el Trabajo será un profesional postgraduado, que poseerá una completa y sólida formación en la higiene, seguridad y riesgos del trabajo, capaz de organizar y dirigir las actividades que sean necesarias en este aspecto, en todo tipo de empresas. El Especialista en Higiene y Seguridad en el Trabajo será poseedor de una actitud crítica y flexible que le permitirá encarar con espíritu docente la difusión de los requisitos de seguridad y trabajar en equipos interdisciplinarios, cumpliendo tareas de docencia y capacitación en temas de higiene y seguridad a todo el personal en la empresa en sus diferentes categorías, y organizando equipos de trabajadores para prevención de riesgos, sin perder de vista el compromiso ético con la sociedad y la defensa de la salud física y psíquica de los trabajadores y del medio ambiente."),
                new Obj_Carreras("Especialización en Informática Educativa", "Dpto. de Educación y Formación Complementaria", "1 año", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=especializacion-en-informatica-educativa", "El egresado es un profesional apto para: \nGenerar, formular, implementar y evaluar proyectos de aplicación innovadores en el área de la Informática Educativa.\nDesarrollar, usar y evaluar sistemas digitales que apliquen conocimiento pedagógico para el descubrimiento de recursos.\nParticipar en grupos de trabajo interdisciplinarios para el desarrollo de proyectos en el campo de la Informática Educativa."),
                new Obj_Carreras("Maestría en Informática Educativa", "Dpto. de Educación y Formación Complementaria", "620 horas", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=maestria-en-informatica-educativa", "El egresado es un profesional apto para: \nGenerar, formular, implementar y evaluar proyectos de aplicación innovadores en el área de la Informática Educativa.\nDesarrollar actividades de investigación en el área de la Informática Educativa.\nCrear, distribuir, compartir y utilizar nuevos conocimientos en el área de la Informática Educativa.\nDesarrollar, usar y evaluar sistemas digitales que apliquen conocimiento pedagógico para el descubrimiento de recursos.\nParticipar en grupos de trabajo interdisciplinarios para el desarrollo de proyectos en el campo de la Informática Educativa.\nParticipar en la formulación de políticas y estrategias para la incorporación de tecnologías informáticas en ámbitos educativos.\n"),
                //Carreras pre-grado
                new Obj_Carreras("","","","","","",""),
                new Obj_Carreras("Programador Universitario en Informatica", "Dpto. de Informatica", "3 años", " 385 450 9560   Int 1816", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=programador-universitario-en-informatica", "El Programador Universitario en Informática posee:\nLos conocimientos básicos (lógico-matemáticos y computacionales) para un adecuado desempeño en su quehacer técnico específico.\nConocimientos específicos sobre técnicas de implementación, prueba y mantenimiento de software.\nUna sólida experiencia práctica en el uso de lenguajes y herramientas informáticas."),
                new Obj_Carreras("Tecnicatura universitaria vial", "Dpto. de Obras Viales", "2 años y medio", " 385 450 9560   Int 1921", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=tecnicatura-universitaria-vial", "El Técnico Universitario Vial debe tener:\nConocimientos básicos de las tecnologías viales para una adecuada fundamentación práctica para su desenvolvimiento como Técnico Universitario vial.\nApropiada preparación y capacidad para realizar ensayos de laboratorio y control de materiales.\nAdecuada formación para colaborar en el control de ejecución o supervisión de Obras Viales.\n"),
                new Obj_Carreras("Tecnicatura universitaria en construcciones", "Dpto. de Estructuras y Construcciones", "2 años y medio", " 385 450 9560   Int 1921", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=tecnicatura-universitaria-en-construccion", "El Técnico Universitario en Construcciones debe tener:\nConocimientos básicos de las ciencias exactas y de las tecnologías para una adecuada fundamentación práctica en su desenvolvimiento como Técnico Universitario en Construcciones.\nApropiada preparación y capacidad para realizar ensayos de laboratorio y control de materiales.\nApropiada preparación y capacidad para realizar cómputos y presupuestos.\nApropiada preparación y capacidad para realizar dibujos y planos, tanto en tablero como en computadora.\nAdecuada formación para colaborar en el control de ejecución o supervisión de obras de la construcción.\nAdecuada formación en trabajo en grupos para poder colaborar en los equipos técnicos interdisciplinarios de obras multipropósitos.\n"),
                new Obj_Carreras("Tecnicatura universitaria en hidrologia subterranea", "Dpto. de Recursos Hídricos", "3 años", " 385 450 9560   Int 1908", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=tecnicatura-universitaria-en-hidrologia-subterranea", "El Técnico Universitario en Hidrología Subterránea tiene:\nUn conocimiento básico de la hidrología de las aguas subterráneasa para un adecuado basamento práctico en su desenvolvimiento como técnico específico.\nApropiada preparación y capacidad para colaborar en la evaluación, exploración y explotación del Recurso Hídrico Subterráneo disponible.\nSólida formación práctica en áreas de su especialidad para analizar e interpretar su campo de aplicación y ser capaz de integrarse a grupos interdisciplinarios.\n"),
                new Obj_Carreras("ETecnicatura universitaria en organizacion y control de la produccion", "Dpto. de Estructuras y Construcciones", "3 años", " 385 450 9560   Int 1921", "Sede Central de la FCEyT", "http://fce.unse.edu.ar/?q=tecnicatura-universitaria-en-organizacion-y-control-de-la-produccion", "El Técnico Universitario en Organización y Control de la Producción tiene:\nConocimientos básicos del contexto teórico soporte de la ciencia aplicada, la técnica y la tecnología.\nConocimientos básicos de las tecnologías de aplicación en el campo electromecánico.\nConocimientos básicos de la disciplina de la ingeniería de producción como integración de los factores que concurren al conjunto productivo.\nHabilidades y destrezas para la aplicación práctica de los conocimientos.\nActitud crítica e innovadora frente a problemas técnicos y cambios tecnológicos.\nActitud de compromiso hacia el comportamiento ético y la preservación del medio ambiente.\n"),
        };
        return ArregloCarreras;
    }
}

